### ISSUE TITLE
'LiteNetLib4MirrorTransport' does not implement inherited abstract member 'Transport.ServerUri()'`

### ISSUE THREAD

**Issue by raultresd** [MichalPetryka/LiteNetLib4Mirror#21]
I imported the latest version of LiteNetLib4Mirror (1.2.8) and the latest version of Mirror(Version 10.4.7) from the Asset Store.
Tested on Unity 2019.3.2f1 and Unity 2018.4.17f1

I get an error right away:
`Assets\Mirror\Runtime\Transport\LiteNetLib4Mirror\LiteNetLib4MirrorTransport.cs(10,15): error CS0534: 'LiteNetLib4MirrorTransport' does not implement inherited abstract member 'Transport.ServerUri()'`

**Comment by Siccity** [comment]
+1

**Comment by dmerner** [comment]
Same over here on 2019.3.6f1 and Mirror 11.4.2

**Comment by swirllyman** [comment]
Any work around for this?

**Comment by dmerner** [comment]
> 
> 
> Any work around for this?

@MrGadget1024 has updated LiteNetLib4Mirror on his branch to work with Mirror 11.4.2 (current version on the Asset Store).  He uploaded the assetpackage to the Mirror Discord.  I've attached it here.

[LiteNetMirror1.2.10.zip](https://github.com/MichalPetryka/LiteNetLib4Mirror/files/4466779/LiteNetMirror1.2.10.zip)
